version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cse-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
      - VITE_WS_URL=ws://localhost:${BACKEND_PORT:-8000}/ws
    depends_on:
      - backend
    networks:
      - cse-network
    restart: unless-stopped
    command: >
      sh -c "if [ '$NODE_ENV' = 'development' ]; then
              npm run dev;
            else
              npm run build && npm run preview;
            fi"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cse-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/app/db/:/app/db/
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=/app/db/sample_data.db
    networks:
      - cse-network
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  cse-network:
    driver: bridge